# Problem 1

In [11]:
!pip install numpy

# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix=np.random.randint(0,11, size=(1,5))
# 3 - matris'in boyutunu öğrenin
print("Matrisin boyutu",matrix.shape)
# 4 - matris'i yeniden boyutlandırın
reshaped_matrix=np.reshape(matrix(5,1))
print("Yeniden boyutlandırılmış Matris",reshaped_matrix)
# 5 - matris'in boyut sayısını öğrenin
print("Matrisin Boyut Sayısı:", reshaped_matrix.ndim)

Matrisin boyutu (1, 5)



[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


TypeError: 'numpy.ndarray' object is not callable

# Problem 2

In [9]:
!pip install numpy


# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
tek_sayilar = np.arange(1, 11, 2)  
matris = np.random.choice(tek_sayilar, size=(3, 3))
print("Oluşturulan Matris:\n", matris)

# 2 - Oluşturduğunuz matrisi parçalayın
parca1, parca2 = np.hsplit(matris, [2])
print("Parça 1:\n", parca1)
print("Parça 2:\n", parca2)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis_matris = np.hstack((parca1, parca2))
print("Birleştirilmiş Matris:\n", birlesmis_matris)


Oluşturulan Matris:
 [[5 1 3]
 [5 7 5]
 [3 3 3]]
Parça 1:
 [[5 1]
 [5 7]
 [3 3]]
Parça 2:
 [[3]
 [5]
 [3]]
Birleştirilmiş Matris:
 [[5 1 3]
 [5 7 5]
 [3 3 3]]



[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# Problem 3

In [10]:
!pip install numpy

# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np
sayi_araligi = np.arange(5, 101, 2)
matris = np.random.choice(sayi_araligi, size=(2, 5))  
print("Oluşturulan Matris:\n", matris)

# 2 - matris'in özelliklerini inceleyin
print("Matrisin Boyutları (Shape):", matris.shape)
print("Matrisin Boyut Sayısı (ndim):", matris.ndim)
print("Matrisin Toplam Eleman Sayısı (Size):", matris.size)
print("Matrisin Elemanlarının Veri Tipi (dtype):", matris.dtype)
print("Matrisin Elemanlarının Toplamı:", matris.sum())


Oluşturulan Matris:
 [[59 39 47 95 83]
 [23 69 15 85 69]]
Matrisin Boyutları (Shape): (2, 5)
Matrisin Boyut Sayısı (ndim): 2
Matrisin Toplam Eleman Sayısı (Size): 10
Matrisin Elemanlarının Veri Tipi (dtype): int64
Matrisin Elemanlarının Toplamı: 584



[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
